"""Export source-checked core citations; no inferred experimental claims."""
from pathlib import Path
import csv,json,hashlib
ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'docs/shared'
entries=[
('wang2025foundation','article',dict(title='Foundation Model for Skeleton-Based Human Action Understanding',author='Wang, Hongsong and Weng, Wanjiang and Wang, Junbo and Zhao, Fang and Xie, Guo-Sen and Geng, Xin and Wang, Liang',year='2025',journal='arXiv preprint arXiv:2508.12586',url='https://arxiv.org/abs/2508.12586',note='DSTE source; cite journal metadata separately when using the published TPAMI version')),
('weng2025usdrl','inproceedings',dict(title='USDRL: Unified Skeleton-Based Dense Representation Learning with Multi-Grained Feature Decorrelation',author='Weng, Wanjiang and Wang, Hongsong and Wang, Junbo and He, Lei and Xie, Guo-Sen',year='2025',booktitle='Proceedings of the AAAI Conference on Artificial Intelligence',doi='10.1609/aaai.v39i8.32899')),
('ultralyticsyolov8','misc',dict(title='Ultralytics YOLOv8 Documentation',author='{Ultralytics}',url='https://docs.ultralytics.com/models/yolov8/',note='Software documentation, accessed 2026-10-02; not an independent peer-reviewed YOLOv8 paper')),
('xu2022vitpose','inproceedings',dict(title='ViTPose: Simple Vision Transformer Baselines for Human Pose Estimation',author='Xu, Yufei and Zhang, Jing and Zhang, Qiming and Tao, Dacheng',year='2022',booktitle='Advances in Neural Information Processing Systems',url='https://proceedings.neurips.cc/paper_files/paper/2022/hash/fbb10d319d44f8c3b4720873e4177c65-Abstract-Conference.html')),
('mehraban2024motionagformer','inproceedings',dict(title='MotionAGFormer: Enhancing 3D Human Pose Estimation With a Transformer-GCNFormer Network',author='Mehraban, Soroush and Adeli, Vida and Taati, Babak',year='2024',booktitle='Proceedings of the IEEE/CVF Winter Conference on Applications of Computer Vision',url='https://openaccess.thecvf.com/content/WACV2024/html/Mehraban_MotionAGFormer_Enhancing_3D_Human_Pose_Estimation_With_a_Transformer-GCNFormer_Network_WACV_2024_paper.html')),
('shahroudy2016ntu','inproceedings',dict(title='NTU RGB+D: A Large Scale Dataset for 3D Human Activity Analysis',author='Shahroudy, Amir and Liu, Jun and Ng, Tian-Tsong and Wang, Gang',year='2016',booktitle='Proceedings of the IEEE Conference on Computer Vision and Pattern Recognition',url='https://openaccess.thecvf.com/content_cvpr_2016/html/Shahroudy_NTU_RGBD_A_CVPR_2016_paper.html')),
('aslan2017fall','article',dict(title='Skeleton Based Efficient Fall Detection',author='Aslan, Muzaffer and Akbulut, Yakup and Şengür, Abdulkadir and İnce, M. Cevdet',year='2017',journal='Journal of the Faculty of Engineering and Architecture of Gazi University',doi='10.17341/gazimmfd.369347')),
('lamsal2026safer','article',dict(title='SAFER-Activities: A Dataset for Smart Assessment of Fall Events and Routine Activities',author='Lamsal, Diwas and Wickramatilake, Pramod and Moonrinta, Jednipat and Ekpanyapong, Mongkol and Dailey, Matthew N.',year='2026',journal='arXiv preprint arXiv:2609.08038',url='https://arxiv.org/abs/2609.08038')),
('charfi2013le2i','article',dict(title='Optimized Spatio-Temporal Descriptors for Real-Time Fall Detection: Comparison of Support Vector Machine and Adaboost-Based Classification',author='Charfi, Imen and Mitéran, Johel and Dubois, Julien and Atri, Mohamed and Tourki, Rached',year='2013',journal='Journal of Electronic Imaging',volume='22',number='4',pages='041106',doi='10.1117/1.JEI.22.4.041106')),
('kwolek2014urfd','article',dict(title='Human Fall Detection on Embedded Platform Using Depth Maps and Wireless Accelerometer',author='Kwolek, Bogdan and Kępski, Michal',year='2014',journal='Computer Methods and Programs in Biomedicine',volume='117',number='3',pages='489--501',url='https://fenix.ur.edu.pl/~mkepski/ds/uf.html',note='Official dataset page specifies this citation')),
('auvinet2010mcfd','techreport',dict(title='Multiple Cameras Fall Dataset',author='Auvinet, E. and Rougier, C. and Meunier, J. and St-Arnaud, A. and Rousseau, J.',year='2010',institution='DIRO, Université de Montréal',number='1350',url='https://www-labs.iro.umontreal.ca/~labimage/Dataset/',note='Consult the 2025 erratum; evaluation held due to scenario23 annotation conflict')),
('kim2024fusion','article',dict(title='Fall Recognition Based on Time-Level Decision Fusion Classification',author='Kim, Juyoung and Kim, Beomseong and Lee, Heesung',year='2024',journal='Applied Sciences',volume='14',number='2',pages='709',doi='10.3390/app14020709')),
('raza2025pose','article',dict(title='Human Fall Detection Using Pose Estimation: From Traditional Machine Learning to Vision Transformers',author='Raza, Ali and Yousaf, Muhammad Haroon and Ahmad, Waqar and Velastin, Sergio A. and Viriri, Serestina',year='2025',journal='Engineering Applications of Artificial Intelligence',volume='143',pages='109809',doi='10.1016/j.engappai.2024.109809')),
('zobi2025vira','article',dict(title='Robust 3D Skeletal Joint Fall Detection in Occluded and Rotated Views Using Data Augmentation and Inference-Time Aggregation',author='Zobi, Maryem and Bolzani, Lorenzo and Tabii, Youness and Oulad Haj Thami, Rachid',year='2025',journal='Sensors',volume='25',number='21',pages='6783',doi='10.3390/s25216783')),
('benabdennour2026fall','article',dict(title='Real-Time Human Fall Detection From Video Using YOLOv11 With Pose Estimation: A Paradigm Shift Toward Efficient Transformer-Based Architectures',author='BenAbdennour, Adel and Sameh, Mahmoud and Khawaja, Bilal A. and Vallappil, Arshad Karimbu and Alenezi, Abdulmajeed M. and Abbasi, Qammer H. and Qazi, Sameer',year='2026',journal='IEEE Access',volume='14',pages='45658--45675',doi='10.1109/ACCESS.2026.3674843')),
('schneider2025omnifallv1','article',dict(title='OmniFall: A Unified Staged-to-Wild Benchmark for Human Fall Detection',author='Schneider, David and Marinov, Zdravko and Baur, Rafael and Zhong, Zeyun and Düger, Rodi and Stiefelhagen, Rainer',year='2025',journal='arXiv preprint arXiv:2505.19889v1',url='https://arxiv.org/html/2505.19889v1',note='Version 1; 10-class taxonomy. Do not mix with the later 16-class synthetic-inclusive version')),
('schneideromnifallupdated','misc',dict(title='OmniFall: From Staged Through Synthetic to Wild, A Unified Multi-Domain Dataset for Robust Fall Detection',author='Schneider, David and Marinov, Zdravko and Mistol, Moritz and Zhong, Zeyun and Jaus, Alexander and Düger, Rodi and Baur, Rafael and Sarfraz, M. Saquib and Stiefelhagen, Rainer',url='https://arxiv.org/abs/2505.19889',note='Updated title and 16-class taxonomy as accessed 2026-10-02; specify the version used when submitting')),
('he2016residual','inproceedings',dict(title='Deep Residual Learning for Image Recognition',author='He, Kaiming and Zhang, Xiangyu and Ren, Shaoqing and Sun, Jian',year='2016',booktitle='Proceedings of the IEEE Conference on Computer Vision and Pattern Recognition',url='https://openaccess.thecvf.com/content_cvpr_2016/html/He_Deep_Residual_Learning_CVPR_2016_paper.html')),
('houlsby2019adapters','inproceedings',dict(title='Parameter-Efficient Transfer Learning for NLP',author='Houlsby, Neil and Giurgiu, Andrei and Jastrzebski, Stanislaw and Morrone, Bruna and De Laroussilhe, Quentin and Gesmundo, Andrea and Attariyan, Mona and Gelly, Sylvain',year='2019',booktitle='Proceedings of the 36th International Conference on Machine Learning',pages='2790--2799',url='https://proceedings.mlr.press/v97/houlsby19a.html')),
('hendrycks2016gelu','article',dict(title='Gaussian Error Linear Units (GELUs)',author='Hendrycks, Dan and Gimpel, Kevin',year='2016',journal='arXiv preprint arXiv:1606.08415',url='https://arxiv.org/abs/1606.08415')),
('loshchilov2019adamw','inproceedings',dict(title='Decoupled Weight Decay Regularization',author='Loshchilov, Ilya and Hutter, Frank',year='2019',booktitle='International Conference on Learning Representations',url='https://arxiv.org/abs/1711.05101')),
]

related=[
['kim2024fusion','RGB -> pose -> ST-GCN -> temporal fusion','HAR-UP target training','action classification with decision fusion','not a matched external benchmark','detector/pose/action pipeline and fusion background','https://www.mdpi.com/2076-3417/14/2/709'],
['raza2025pose','multiple pose estimators and classifiers','UR-Fall, UP-Fall, Le2i; 70/30 and 10-fold CV stated','grouping unit unresolved in reviewed method description','target training differs from frozen external evaluation','pose and classifier comparison','https://e-archivo.uc3m.es/rest/api/core/bitstreams/97f6c756-c0f9-4eea-b77a-fd8afe0578a0/content'],
['zobi2025vira','3D GCN; rotation/occlusion augmentation; inference aggregation','Le2i source video split before augmentation','augmented skeleton sequence classification','not untreated unseen-target evaluation','view robustness and skeleton mapping','https://pmc.ncbi.nlm.nih.gov/articles/PMC12609388/'],
['benabdennour2026fall','YOLOv11-Pose + temporal Transformer','multi-source training; no Le2i fine-tuning','835 selected clips from 109 Le2i videos; F1 91.65%','excludes boundary and post-fall; not full-video event F1','external transfer and explicitly defined label unit','https://eprints.gla.ac.uk/384046/1/384046.pdf'],
['schneider2025omnifallv1','frozen RGB backbones; shared annotations','staged cross-subject/view -> OOPS wild','10-class v1; later version changes taxonomy','MCFD appears in staged training protocols','protocol harmonization and domain shift','https://arxiv.org/html/2505.19889v1'],
['lamsal2026safer','skeleton / frozen RGB / fusion','in-lab, OOD, cross-dataset','dense action labels','direct source dataset; baseline results are not ours','label granularity and source-to-target evaluation','https://arxiv.org/abs/2609.08038'],
]

def main():
    path=OUT/'2026-10-02_paper_core_references.bib'
    chunks=['% Core citations for DOC-20261002-paper-evidence-review-R1.','% Background citations do not establish historical design provenance or experimental superiority.']
    for key,kind,fields in entries:
        chunks.append('@'+kind+'{'+key+',\n'+''.join(f'  {name} = {{{value}}},\n' for name,value in fields.items())+'}\n')
    path.write_text('\n'.join(chunks)+'\n')
    csvpath=OUT/'2026-10-02_related_work_matrix.csv'
    with csvpath.open('w',newline='') as f:
        w=csv.writer(f);w.writerow(['citation_key','method','training_data_protocol','evaluation_unit','comparability_limit','relevance','primary_source']);w.writerows(related)
    evidence=dict(document_id='DOC-20261002-paper-evidence-review-R1',citations=len(entries),related_studies=len(related),
        search_workstreams=3,search_calls=4,requested_search_result_slots=30,
        note='Search result slots include duplicates; not 30 unique fully read papers. Direct fetches are additional.',
        outputs={str(p.relative_to(ROOT)):hashlib.sha256(p.read_bytes()).hexdigest() for p in [path,csvpath]})
    (ROOT/'docs/internal/2026-10-02_evidence_audit/literature_exports.json').write_text(json.dumps(evidence,indent=2)+'\n')
    print(json.dumps(evidence,indent=2))

if __name__=='__main__':main()
